version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - jtms-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin}"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - jtms-network
    restart: unless-stopped

  user-service:
    depends_on:
      - postgres
      - discovery-service
    image: manuellarbi/jtms-user-service:base
    container_name: user-service
    ports:
      - "4400:4400"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jtms_user_management_service
      - SERVER_PORT=4400
      - MAILHOST=sandbox.smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - SERVICE_EMAIL=jtms@mail.com
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_SAMPLE_RATE=1.0
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=14400000
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka
      - FRONT_END_BASE_URL=http://localhost:4200
      - FRONTEND_LOGIN_ROUTE=/login
      - FRONTEND_RESET_PASSWORD_ROUTE=/password-update
      - APP_NAME="JTMS User Management Service"
    networks:
      - jtms-network
    restart: unless-stopped


  gateway-service:
    image: manuellarbi/jtms-api-gateway:base
    container_name: api-gateway
    ports:
      - "4000:2024"
    depends_on:
      - discovery-service
    environment:
      - APPLICATION_NAME="JTMS-API-Gateway-Service"
      - SERVER_PORT=2024
      - JWT_SECRET=${JWT_SECRET}
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka
    networks:
      - jtms-network
    restart: unless-stopped


  discovery-service:
    image: manuellarbi/jtms-service-discovery:base
    container_name: discovery-service
    ports:
      - "4001:4001"
    environment:
      - SERVER_PORT=4001
    networks:
      - jtms-network
    restart: unless-stopped

  assessment-service:
    depends_on:
      - postgres
    image: zena07/assessment-service:latest
    container_name: assessment-service
    ports:
      - "4002:4002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/assessment
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - DB_HOST=localhost
      - DB_PORT=5431
      - DB=assessment
      - PORT=4002
    networks:
      - jtms-network
    restart: unless-stopped


  curriculum-service:
    depends_on:
      - postgres
    image: elitekaycy/curriculum:latest
    container_name: curriculum-service
    ports:
      - "4003:4003"
    environment:
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/curriculum_db
      - SENTRY_DSN=${SENTRY_DSN}
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=4003
    networks:
      - jtms-network
    restart: unless-stopped

networks:
  jtms-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
